### ISSUE TITLE
RFLink on Win Rechner (Migration Win -> Win) "cannot find adapter "rflink@2.1.6"

### ISSUE THREAD

**Issue by klassisch** [ioBroker/ioBroker.rflink#42]
Issue also decribed in Foum https://forum.iobroker.net/topic/60173/rflink-auf-win-rechner-cannot-find-adapter-rflink-2-1-6?_=1669338504851 
* Migration form Win 10 Platform to Win 10 Platform: iobroker-data copied
* RFLink Adapter is shown in instances list but nor functional: No serial port shown even connected to RFLink
* Following the install log file Phytho 3 and "Visual Studio 2020" installed
* Guess: Rebuild of serial interface failed
* Extract from install log:
`
1378 timing command:install Completed in 18046ms
1379 verbose stack Error: command failed
1379 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
1379 verbose stack     at ChildProcess.emit (node:events:527:28)
1379 verbose stack     at maybeClose (node:internal/child_process:1092:16)
1379 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
1380 verbose pkgid @serialport/bindings@8.0.8
1381 verbose cwd C:\ioBroker
1382 verbose Windows_NT 10.0.19044
1383 verbose node v16.15.1
1384 verbose npm  v8.11.0
1385 error code 1
1386 error path C:\ioBroker\node_modules\iobroker.rflink\node_modules\@serialport\bindings
1387 error command failed
1388 error command C:\Windows\system32\cmd.exe /d /s /c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
1389 error gyp info it worked if it ends with ok
1389 error gyp info using node-gyp@8.4.1
1389 error gyp info using node@16.15.1 | win32 | x64
1389 error gyp info find Python using Python version 3.10.8 found at "c:\Users\JS\AppData\Local\Programs\Python\Python310\python.exe"
1389 error gyp ERR! find VS 
1389 error gyp ERR! find VS msvs_version not set from command line or npm config
1389 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
1389 error gyp ERR! find VS checking VS2022 (17.4.33110.190) found at:
1389 error gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
1389 error gyp ERR! find VS - found "Visual Studio C++ core features"
1389 error gyp ERR! find VS - missing any VC++ toolset
1389 error gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
1389 error gyp ERR! find VS looking for Visual Studio 2015
1389 error gyp ERR! find VS - not found
1389 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
1389 error gyp ERR! find VS 
1389 error gyp ERR! find VS **************************************************************
1389 error gyp ERR! find VS You need to install the latest version of Visual Studio
1389 error gyp ERR! find VS including the "Desktop development with C++" workload.
1389 error gyp ERR! find VS For more information consult the documentation at:
1389 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
1389 error gyp ERR! find VS **************************************************************
1389 error gyp ERR! find VS 
1389 error gyp ERR! configure error 
1389 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
1389 error gyp ERR! stack     at VisualStudioFinder.fail (C:\ioBroker\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
1389 error gyp ERR! stack     at C:\ioBroker\node_modules\node-gyp\lib\find-visualstudio.js:75:16
1389 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\ioBroker\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
1389 error gyp ERR! stack     at C:\ioBroker\node_modules\node-gyp\lib\find-visualstudio.js:71:14
1389 error gyp ERR! stack     at C:\ioBroker\node_modules\node-gyp\lib\find-visualstudio.js:384:16
1389 error gyp ERR! stack     at C:\ioBroker\node_modules\node-gyp\lib\util.js:54:7
1389 error gyp ERR! stack     at C:\ioBroker\node_modules\node-gyp\lib\util.js:33:16
1389 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
1389 error gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
1389 error gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
1389 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
1389 error gyp ERR! System Windows_NT 10.0.19044
1389 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ioBroker\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
1389 error gyp ERR! cwd C:\ioBroker\node_modules\iobroker.rflink\node_modules\@serialport\bindings
1389 error gyp ERR! node -v v16.15.1
1389 error gyp ERR! node-gyp -v v8.4.1
1389 error gyp ERR! not ok
1390 verbose exit 1
`

**Comment by Apollon77** [comment]
Ja da fehlen noch build tools ... oder upgrade auf serialport 10

**Comment by klassisch** [comment]
Vielen Dank! Wie und wo kann ich im Adapter auf serailport 10 upgraden?

**Comment by Apollon77** [comment]
Muss ein Dev machen. Keine Ahnung warum windows manchmal bei "Build kram" so zickig ist :-(

**Comment by klassisch** [comment]
Das wird wohl daran liegen, daß mein Produktivrechner kein Entwicklungsrechner ist und ich kein Entwickler.

Mittlerweile läuft die Übersetzung. Visual Studio benötigt zusätzliche Plugins (Workloads) und Komponenten. 
Installiert habe ich:
![grafik](https://user-images.githubusercontent.com/35134055/204063373-16fa3969-a368-40d8-a73e-038c1930d59f.png)

Davon wird Desktop C++ ganz sicher gebraucht. 

vorsichtshalber noch Linux Workload
![grafik](https://user-images.githubusercontent.com/35134055/204063438-68bb29cb-8fd6-4760-b898-a0f9fdf47c40.png)

Und sicher gebraucht wird auch ein passendes Windosw SDK. Der Installer hatte unglücklicherweise Win 11 SDK auf dem Win 10 Rechner installiert. Habe die Win 10 SDKs nachgeordert.

![grafik](https://user-images.githubusercontent.com/35134055/204063534-c2dec87a-f3fb-4cd5-9435-57b5fa8307f2.png)


Danach lief die Übersetzung durch und die serielle Schnittstelle kann ausgewählt werden.
