### ISSUE TITLE
kann RFLINK nicht (neu) installieren

### ISSUE THREAD

**Issue by der-oBi** [ioBroker/ioBroker.rflink#43]
Leider funktionierte mein RFLINK Adapter vor kurzem nicht mehr. Ich konnte in den Einstellungen der Instanz auch keinen COM-Port mehr auswählen. Nach langem hin und her, habe ich den Adapter gelöscht und wollte ihn neu installieren. Das geht nun auch nicht mehr :-(

Hoffentlich kann mir jemand sagen, was ich falsch mache...

Hier die Meldung im iobroker:
```
$ iobroker add rflink auto --host ioBrokerDebian --debug
Installing iobroker.rflink@2.1.6... (System call)
npm WARN skipping integrity check for git dependency ssh://git@github.com/noopkat/browser-serialport.git
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated uuid@2.0.3: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm WARN deprecated jscs@3.0.7: JSCS has merged with ESLint! See - https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
host.ioBrokerDebian Cannot install iobroker.rflink@2.1.6: 1
ERROR: Process exited with code 25
```

Und hier die letzten Zeilen des Log-Files:
```
890 timing build:run:install:node_modules/mdns Completed in 13ms
891 info run unix-dgram@2.0.4 install node_modules/unix-dgram node-gyp rebuild
892 info run unix-dgram@2.0.4 install { code: 'ENOENT', signal: undefined }
893 verbose reify failed optional dependency /opt/iobroker/node_modules/unix-dgram
894 silly reify mark deleted [ '/opt/iobroker/node_modules/unix-dgram' ]
895 timing build:run:install:node_modules/unix-dgram Completed in 13ms
896 timing reify:rollback:createSparse Completed in 556ms
897 timing reify:rollback:retireShallow Completed in 12ms
898 timing command:install Completed in 13358ms
899 verbose stack Error: command failed
899 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
899 verbose stack     at ChildProcess.emit (node:events:513:28)
899 verbose stack     at maybeClose (node:internal/child_process:1091:16)
899 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
900 verbose pkgid @serialport/bindings@8.0.8
901 verbose cwd /opt/iobroker
902 verbose Linux 5.15.64-1-pve
903 verbose node v18.12.1
904 verbose npm  v8.19.2
905 error code 1
906 error path /opt/iobroker/node_modules/@serialport/bindings
907 error command failed
908 error command sh -c -- prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
909 error node:internal/modules/cjs/loader:998
909 error   throw err;
909 error   ^
909 error
909 error Error: Cannot find module 'object-assign'
909 error Require stack:
909 error - /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/render-template.js
909 error - /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/plumbing.js
909 error - /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/index.js
909 error - /usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/npmlog/log.js
909 error - /usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js
909 error - /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
909 error     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
909 error     at Module._load (node:internal/modules/cjs/loader:841:27)
909 error     at Module.require (node:internal/modules/cjs/loader:1061:19)
909 error     at require (node:internal/modules/cjs/helpers:103:18)
909 error     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/render-template.js:4:20)
909 error     at Module._compile (node:internal/modules/cjs/loader:1159:14)
909 error     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
909 error     at Module.load (node:internal/modules/cjs/loader:1037:32)
909 error     at Module._load (node:internal/modules/cjs/loader:878:12)
909 error     at Module.require (node:internal/modules/cjs/loader:1061:19) {
909 error   code: 'MODULE_NOT_FOUND',
909 error   requireStack: [
909 error     '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/render-template.js',
909 error     '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/plumbing.js',
909 error     '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/gauge/index.js',
909 error     '/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/npmlog/log.js',
909 error     '/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js',
909 error     '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
909 error   ]
909 error }
909 error
909 error Node.js v18.12.1
910 verbose exit 1
911 timing npm Completed in 13558ms
912 verbose unfinished npm timer reify 1669558369699
913 verbose unfinished npm timer reify:build 1669558382174
914 verbose unfinished npm timer build 1669558382176
915 verbose unfinished npm timer build:deps 1669558382176
916 verbose unfinished npm timer build:run:install 1669558382189
917 verbose unfinished npm timer build:run:install:node_modules/@serialport/bindings 1669558382190
918 verbose code 1
919 error A complete log of this run can be found in:
919 error     /home/iobroker/.npm/_logs/2022-11-27T14_12_49_509Z-debug-0.log
```

**Comment by Apollon77** [comment]
Error 25 ... see https://forum.iobroker.net/topic/57337/fehler-25-bei-adapter-install-update-mit-npm8
