### ISSUE TITLE
Show correct version of firmware installed

### ISSUE THREAD

**Issue by padrino-x** [ioBroker/ioBroker.rflink#45]
Though I have Firmware 1.51 installed in the meantime

rflink.0.firmwareVersion

still shows V1.1 - R48 (is that hard coced?)

**Comment by fraeggle** [comment]
have the same issue.
Think its hardcoded.
Maybe ther will be a solution.

![grafik](https://github.com/ioBroker/ioBroker.rflink/assets/40692505/9085ab78-5f2a-4653-ab9f-980c9d638cf9)

**Comment by fraeggle** [comment]
======== Start marking the full check here =========

```
Skript v.2023-10-10

*** BASE SYSTEM ***
   Static hostname: ioB
         Icon name: computer
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 5.10.103-v7l+
      Architecture: arm

Model           : Raspberry Pi 4 Model B Rev 1.4
Docker          : false
Virtualization  : none
Kernel          : armv7l
Userland        : armhf

Systemuptime and Load:
 15:01:02 up 5 days,  7:55,  1 user,  load average: 0.62, 0.39, 0.26
CPU threads: 4


*** RASPBERRY THROTTLING ***
Current issues:
No throttling issues detected.

Previously detected issues:
~ Under-voltage has occurred
~ Arm frequency capping has occurred

*** Time and Time Zones ***
               Local time: Wed 2024-02-14 15:01:03 CET
           Universal time: Wed 2024-02-14 14:01:03 UTC
                 RTC time: Wed 2024-02-14 14:01:03
                Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

*** User and Groups ***
pi
/home/pi
pi adm tty dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi iobroker

*** X-Server-Setup ***
X-Server:       false
Desktop:
Terminal:       tty
Boot Target:    graphical.target

*** MEMORY ***
              total        used        free      shared  buff/cache   available
Mem:           3.8G        1.8G        1.1G         25M        891M        1.9G
Swap:            0B          0B          0B
Total:         3.8G        1.8G        1.1G

         3838 M total memory
         1806 M used memory
          437 M active memory
         2123 M inactive memory
         1140 M free memory
          191 M buffer memory
          700 M swap cache
            0 M total swap
            0 M used swap
            0 M free swap

Raspberry only:
oom events: 0
lifetime oom required: 0 Mbytes
total time in oom handler: 0 ms
max time spent in oom handler: 0 ms

*** FAILED SERVICES ***

  UNIT                 LOAD   ACTIVE SUB    DESCRIPTION
* fake-hwclock.service loaded failed failed LSB: Restore / save the current clock  -->  RTC Modul vorhanden
* influxdb.service     loaded failed failed InfluxDB is an open-source, distributed, time series database  -- > läuft auf einem anderen Rechner

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.

*** FILESYSTEM ***
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4       29G  9.2G   19G  33% /
devtmpfs       devtmpfs  1.8G     0  1.8G   0% /dev
tmpfs          tmpfs     1.9G     0  1.9G   0% /dev/shm
tmpfs          tmpfs     1.9G   25M  1.9G   2% /run
tmpfs          tmpfs     5.0M  4.0K  5.0M   1% /run/lock
tmpfs          tmpfs     1.9G     0  1.9G   0% /sys/fs/cgroup
tmpfs          tmpfs     100M  500K  100M   1% /mnt/ramdisk
/dev/mmcblk0p1 vfat      253M   49M  204M  20% /boot
tmpfs          tmpfs     384M     0  384M   0% /run/user/1000

Messages concerning ext4 filesystem in dmesg:
[Fri Feb  9 07:05:23 2024] Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1  smsc95xx.macaddr=E4:5F:01:12:C2:1A vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=tty1 root=PARTUUID=6c4add15-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[Fri Feb  9 07:05:24 2024] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[Fri Feb  9 07:05:24 2024] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[Fri Feb  9 07:05:26 2024] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)

Show mounted filesystems \(real ones only\):
TARGET        SOURCE         FSTYPE OPTIONS
/             /dev/mmcblk0p2 ext4   rw,noatime
|-/sys/fs/bpf none           bpf    rw,nosuid,nodev,noexec,relatime,mode=700
`-/boot       /dev/mmcblk0p1 vfat   rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro

Files in neuralgic directories:

/var:
597M    /var/
382M    /var/cache
376M    /var/cache/apt
317M    /var/cache/apt/archives
98M     /var/lib

Archived and active journals take up 24.0M in the file system.

/opt/iobroker/backups:
1017M   /opt/iobroker/backups/

/opt/iobroker/iobroker-data:
608M    /opt/iobroker/iobroker-data/
355M    /opt/iobroker/iobroker-data/files
137M    /opt/iobroker/iobroker-data/backup-objects
96M     /opt/iobroker/iobroker-data/files/vis.0
67M     /opt/iobroker/iobroker-data/files/javascript.admin

The five largest files in iobroker-data are:
22M     /opt/iobroker/iobroker-data/files/web.admin/static/js/main.c05ba1d3.js.map
16M     /opt/iobroker/iobroker-data/objects.jsonl
9.2M    /opt/iobroker/iobroker-data/files/vis.0/main/vis-views.json
8.6M    /opt/iobroker/iobroker-data/objects.json.migrated
8.6M    /opt/iobroker/iobroker-data/objects.json.bak.migrated

USB-Devices by-id:
USB-Sticks -  Avoid direct links to /dev/* in your adapter setups, please always prefer the links 'by-id':

/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
/dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.25__Embed_with_CMSIS-DAP_L1100LR4-if03
/dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.25__Embed_with_CMSIS-DAP_L1100LR4-if00

*** NodeJS-Installation ***

/usr/bin/nodejs         v18.17.1
/usr/bin/node           v18.17.1
/usr/bin/npm            9.6.7
/usr/bin/npx            9.6.7
/usr/bin/corepack       0.18.0


nodejs:
  Installed: 18.17.1-deb-1nodesource1
  Candidate: 18.17.1-deb-1nodesource1
  Version table:
 *** 18.17.1-deb-1nodesource1 500
        500 https://deb.nodesource.com/node_18.x buster/main armhf Packages
        100 /var/lib/dpkg/status
     10.24.0~dfsg-1~deb10u3 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages

Temp directories causing npm8 problem: 0
No problems detected

Errors in npm tree:
npm ERR! code ELSPROBLEMS
npm ERR! extraneous: @node-red/node-addon-api@ /opt/iobroker/node_modules/@node-red/node-addon-api
npm ERR! invalid: iobroker.mytime@0.6.1 /opt/iobroker/node_modules/iobroker.mytime
npm ERR! invalid: xmlbuilder@0.4.2 /opt/iobroker/node_modules/homematic-xmlrpc/node_modules/xmlbuilder
npm ERR! invalid: browser-serialport@2.0.3 /opt/iobroker/node_modules/browser-serialport
npm ERR! invalid: node-addon-api@ /opt/iobroker/node_modules/@node-red/editor-api/node_modules/node-addon-api

npm ERR! A complete log of this run can be found in: /home/pi/.npm/_logs/2024-02-14T14_01_16_661Z-debug-0.log

*** ioBroker-Installation ***

ioBroker Status
iobroker is running on this host.


Objects type: jsonl
States  type: jsonl

Core adapters versions
js-controller:  5.0.17
admin:          6.13.16
javascript:     7.1.6

npm ERR! code ELSPROBLEMS
npm ERR! extraneous: @node-red/node-addon-api@ /opt/iobroker/node_modules/@node-red/node-addon-api
npm ERR! invalid: iobroker.mytime@0.6.1 /opt/iobroker/node_modules/iobroker.mytime

npm ERR! A complete log of this run can be found in: /home/pi/.npm/_logs/2024-02-14T14_01_36_951Z-debug-0.log
Adapters from github:   1

Adapter State
+ system.adapter.admin.0                  : admin                 : ioB                                      -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
+ system.adapter.alexa2.0                 : alexa2                : ioB                                      -  enabled
+ system.adapter.backitup.0               : backitup              : ioB                                      -  enabled
  system.adapter.birthdays.0              : birthdays             : ioB                                      -  enabled
  system.adapter.daswetter.0              : daswetter             : ioB                                      -  enabled
  system.adapter.dwd.0                    : dwd                   : ioB                                      -  enabled
+ system.adapter.email.0                  : email                 : ioB                                      -  enabled
  system.adapter.flot.0                   : flot                  : ioB                                      - disabled
+ system.adapter.hm-rega.0                : hm-rega               : ioB                                      -  enabled
+ system.adapter.hm-rpc.0                 : hm-rpc                : ioB                                      -  enabled, port: 0
+ system.adapter.hm-rpc.1                 : hm-rpc                : ioB                                      -  enabled, port: 0
  system.adapter.ical.0                   : ical                  : ioB                                      -  enabled
  system.adapter.ical.1                   : ical                  : ioB                                      -  enabled
+ system.adapter.influxdb.0               : influxdb              : ioB                                      -  enabled, port: 8087
+ system.adapter.javascript.0             : javascript            : ioB                                      -  enabled
+ system.adapter.mqtt.0                   : mqtt                  : ioB                                      -  enabled, port: 1883, bind: 0.0.0.0
+ system.adapter.mytime.0                 : mytime                : ioB                                      -  enabled
+ system.adapter.nina.0                   : nina                  : ioB                                      -  enabled
+ system.adapter.node-red.0               : node-red              : ioB                                      -  enabled, port: 1880, bind: 192xxxxxxxxxxx
  system.adapter.onvif.0                  : onvif                 : ioB                                      - disabled, port: 80, 7575, 8000, 8080, 8081, 8899
+ system.adapter.rflink.0                 : rflink                : ioB                                      -  enabled
+ system.adapter.rflink.1                 : rflink                : ioB                                      -  enabled
+ system.adapter.rpi2.0                   : rpi2                  : ioB                                      -  enabled
+ system.adapter.shelly.0                 : shelly                : ioB                                      -  enabled, port: 1882, bind: 192xxxxxxxxxxx
+ system.adapter.tankerkoenig.0           : tankerkoenig          : ioB                                      -  enabled
+ system.adapter.tr-064.0                 : tr-064                : ioB                                      -  enabled
+ system.adapter.tr-064.1                 : tr-064                : ioB                                      -  enabled
+ system.adapter.trashschedule.0          : trashschedule         : ioB                                      -  enabled
+ system.adapter.tuya.0                   : tuya                  : ioB                                      -  enabled
  system.adapter.vis-canvas-gauges.0      : vis-canvas-gauges     : ioB                                      - disabled
  system.adapter.vis-colorpicker.0        : vis-colorpicker       : ioB                                      -  enabled
  system.adapter.vis-hqwidgets.0          : vis-hqwidgets         : ioB                                      - disabled
  system.adapter.vis-icontwo.0            : vis-icontwo           : ioB                                      - disabled
+ system.adapter.vis-inventwo.0           : vis-inventwo          : ioB                                      -  enabled
  system.adapter.vis-jqui-mfd.0           : vis-jqui-mfd          : ioB                                      - disabled
  system.adapter.vis-lcars.0              : vis-lcars             : ioB                                      - disabled
  system.adapter.vis-timeandweather.0     : vis-timeandweather    : ioB                                      - disabled
  system.adapter.vis.0                    : vis                   : ioB                                      -  enabled
+ system.adapter.web.0                    : web                   : ioB                                      -  enabled, port: 8082, bind: 0.0.0.0, run as: admin
+ system.adapter.wiffi-wz.0               : wiffi-wz              : ioB                                      -  enabled
+ system.adapter.zigbee.0                 : zigbee                : ioB                                      -  enabled, port: /dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.25__Embed_with_CMSIS-DAP_L1100LR4-if00

+ instance is alive

Enabled adapters with bindings
+ system.adapter.admin.0                  : admin                 : ioB                                      -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
+ system.adapter.hm-rpc.0                 : hm-rpc                : ioB                                      -  enabled, port: 0
+ system.adapter.hm-rpc.1                 : hm-rpc                : ioB                                      -  enabled, port: 0
+ system.adapter.influxdb.0               : influxdb              : ioB                                      -  enabled, port: 8087
+ system.adapter.mqtt.0                   : mqtt                  : ioB                                      -  enabled, port: 1883, bind: 0.0.0.0
+ system.adapter.node-red.0               : node-red              : ioB                                      -  enabled, port: 1880, bind: 192xxxxxxxxxxx
+ system.adapter.shelly.0                 : shelly                : ioB                                      -  enabled, port: 1882, bind: 192xxxxxxxxxxx
+ system.adapter.web.0                    : web                   : ioB                                      -  enabled, port: 8082, bind: 0.0.0.0, run as: admin
+ system.adapter.zigbee.0                 : zigbee                : ioB                                      -  enabled, port: /dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.25__Embed_with_CMSIS-DAP_L1100LR4-if00

ioBroker-Repositories
Stable (default): http://download.iobroker.net/sources-dist.json
Beta (latest) : http://download.iobroker.net/sources-dist-latest.json

Active repo(s): Stable (default)

Installed ioBroker-Instances
Used repository: Stable (default)
Adapter    "admin"        : 6.13.16  , installed 6.13.16
Adapter    "alexa2"       : 3.26.4   , installed 3.26.4
Adapter    "backitup"     : 2.9.8    , installed 2.9.8
Adapter    "birthdays"    : 2.4.1    , installed 2.4.1
Adapter    "daswetter"    : 3.1.13   , installed 3.1.13
Adapter    "dwd"          : 2.8.5    , installed 2.8.5
Adapter    "email"        : 1.2.2    , installed 1.2.2
Adapter    "flot"         : 1.12.0   , installed 1.12.0
Adapter    "hm-rega"      : 4.0.0    , installed 4.0.0
Adapter    "hm-rpc"       : 1.16.0   , installed 1.16.0
Adapter    "ical"         : 1.13.3   , installed 1.13.3
Adapter    "influxdb"     : 4.0.2    , installed 3.2.0  [Updatable]
Adapter    "javascript"   : 7.8.0    , installed 7.1.6  [Updatable]
Controller "js-controller": 5.0.17   , installed 5.0.17
Adapter    "mqtt"         : 5.2.0    , installed 5.1.0  [Updatable]
Adapter    "nina"         : 0.0.25   , installed 0.0.25
Adapter    "node-red"     : 5.1.0    , installed 5.1.0
Adapter    "onvif"        : 1.1.1    , installed 1.1.1
Adapter    "rflink"       : 2.1.6    , installed 2.1.6
Adapter    "rpi2"         : 1.3.2    , installed 1.3.2
Adapter    "shelly"       : 6.6.1    , installed 6.6.1
Adapter    "simple-api"   : 2.7.2    , installed 2.7.2
Adapter    "socketio"     : 6.6.0    , installed 6.6.0
Adapter    "tankerkoenig" : 3.3.7    , installed 3.3.7
Adapter    "tr-064"       : 4.2.18   , installed 4.2.18
Adapter    "trashschedule": 2.3.0    , installed 2.3.0
Adapter    "tuya"         : 3.15.0   , installed 3.15.0
Adapter    "vis"          : 1.5.4    , installed 1.5.4
Adapter    "vis-canvas-gauges": 1.0.1, installed 1.0.1
Adapter    "vis-colorpicker": 2.0.3  , installed 2.0.3
Adapter    "vis-hqwidgets": 1.4.0    , installed 1.4.0
Adapter    "vis-icontwo"  : 1.3.0    , installed 1.3.0
Adapter    "vis-inventwo" : 3.3.3    , installed 3.3.3
Adapter    "vis-jqui-mfd" : 1.0.12   , installed 1.0.12
Adapter    "vis-lcars"    : 1.1.1    , installed 1.1.1
Adapter    "vis-timeandweather": 1.2.2, installed 1.2.2
Adapter    "web"          : 6.2.3    , installed 6.2.3
Adapter    "wiffi-wz"     : 2.2.1    , installed 2.2.1
Adapter    "ws"           : 2.5.10   , installed 2.5.10
Adapter    "zigbee"       : 1.10.1   , installed 1.10.1

Objects and States
Please stand by - This may take a while
Objects:        10711
States:         9159

*** OS-Repositories and Updates ***
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 https://repos.influxdata.com/debian stable InRelease
Hit:3 https://repos.influxdata.com/debian buster InRelease
Hit:4 https://deb.nodesource.com/node_18.x buster InRelease
Hit:5 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists...
Pending Updates: 11


*** Log File - Last 25 Lines ***

2024-02-14 01:21:45.758  - error: wiffi-wz.0 (1163) Exception-Code: ECONNRESET: read ECONNRESET
2024-02-14 01:21:47.508  - error: host.ioB instance system.adapter.wiffi-wz.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-02-14 08:05:20.091  - warn: rflink.0 (4390) Wrong serial data: BLDEBUG=ffc9b4cbf577fb92ff
2024-02-14 10:54:26.413  - warn: rflink.0 (4390) Wrong serial data: BLDEBUG=000000000400064008
2024-02-14 11:28:17.015  - warn: rflink.0 (4390) Wrong serial data: BLDEBUG=ffc9b4cbf577afaebf
2024-02-14 11:43:18.840  - warn: rflink.0 (4390) Wrong serial data: BLDEBUG=a65fabbd2b2d7eeb55
2024-02-14 11:56:59.031  - warn: rflink.0 (4390) Wrong serial data: BLDEBUG=b4cbf577ad5b5fa56a
2024-02-14 14:56:32.533  - error: host.ioB Invalid request getRepository. "callback"(false) or "from"(true) is null
2024-02-14 15:01:46.124  - error: tankerkoenig.0 (1091) [ Adapter V:3.3.7 requestData axios: 1.6.5 ] Error: Error: connect ETIMEDOUT 188.68.35.147:443 Error Code ETIMEDOUT Error Message connect ETIMEDOUT 188.68.35.147:443 >>> Stack: Error: connect ETIMEDOUT 188.68.35.147:443
    at Function.AxiosError.from (/opt/iobroker/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/axios/lib/adapters/http.js:610:25)
    at RedirectableRequest.emit (node:events:514:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:526:35)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:489:12)

```

============ Mark until here for C&P =============

**Comment by Matzebhv** [comment]
Same Problem here.
